services:
  dozzle:
    restart: always
    image: whatwewant/dozzle:${SERVICE_DOZZLE_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_DOZZLE_PORT}:${SERVICE_DOZZLE_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
  default:
    external: true
    name: compose-ingress
